export const COMMAND_NAMES = {
  DOCTOR: "sdd-stack:doctor",
  BOOTSTRAP_CHECK: "sdd-stack:bootstrap-check",
  MODELS: "sdd-stack:models",
  TDD_MODE: "sdd-stack:tdd-mode",
  STATUS: "sdd-stack:status",
  CONTINUE: "sdd-stack:continue",
  BROWNFIELD_ONBOARD: "sdd-stack:brownfield-onboard",
  GREENFIELD_ONBOARD: "sdd-stack:greenfield-onboard",
  CURRENT_STATE_EXPLORE: "sdd-stack:current-state-explore",
  DOCUMENTATION_REVIEW: "sdd-stack:documentation-review",
  INIT: "sdd-stack:init",
  PRD: "sdd-stack:prd",
  REQUESTED_DOMAINS: "sdd-stack:requested-domains",
  PLAN: "sdd-stack:plan",
  SPEC: "sdd-stack:spec",
  DESIGN: "sdd-stack:design",
  TASKS: "sdd-stack:tasks",
  APPLY: "sdd-stack:apply",
  VERIFY: "sdd-stack:verify",
  ARCHIVE: "sdd-stack:archive",
  BUGFIX_MEMORY: "sdd-stack:bugfix-memory",
  RESUME: "sdd-stack:resume",
  MEMORY_SEARCH: "sdd-stack:memory-search",
} as const;
